/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.Fleet;
import Business.Flight;
import Business.FlightSchedule;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditi
 */
public class ManageFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightJPanel
     */
     
 Airliner airliner;
 JPanel userProcessContainer;
 AirlinerDirectory airlinerDir;
 List<Flight> flightList;
 List<FlightSchedule> flightSchedule;
 Fleet airplaneList;
    public ManageFlightJPanel(JPanel UserProcessContainer,  Airliner airliner,AirlinerDirectory ad,List<Flight> flightList, List<FlightSchedule> flightSchedule,Fleet airplaneList) {
        initComponents();
        this.airliner=airliner;
        this.userProcessContainer=UserProcessContainer;
        this.airlinerDir= ad;
        this.flightList=flightList;
        this.flightSchedule=flightSchedule;
        lblAirlinerName.setText(airliner.getAirLinerName());
        this.airplaneList=airplaneList;
        if(!flightList.isEmpty())
        {
            populateFlightTable();
        }
        
    }

    void populateFlightTable(){
        lblAirlinerName.setText(airliner.getAirLinerName());
        //populate table
         DefaultTableModel model = (DefaultTableModel) tblFlight.getModel();
        model.setRowCount(0);
        //List<Flight> flightList = airliner.getfArrayList();
        for (Flight s : flightList) {
            //check airline name in airplane
            if(s.getAirlinerName().equals(airliner.getAirLinerName()))
            {
            Object row[] = new Object[2];
            row[0] = s;
            row[1] = s.getFlightName();
            
            model.addRow(row); 
            }
            
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNewFlight = new javax.swing.JButton();
        btnViewFlight = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblAirlinerName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        label1.setAlignment(java.awt.Label.RIGHT);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Airliner Name:");

        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Flight Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFlight);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Flights");

        btnNewFlight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewFlight.setText("Manage Flight");
        btnNewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFlightActionPerformed(evt);
            }
        });

        btnViewFlight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewFlight.setText("View Flight Schedule");
        btnViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("<Back");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAirlinerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBack)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnNewFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAirlinerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(200, 232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewFlight)
                    .addComponent(btnViewFlight))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightActionPerformed
        // TODO add your handling code here:
        //call manageFlightSchdeule for flight
        
        int row = tblFlight.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Flight flight= (Flight)  tblFlight.getValueAt(row,0);
        AirlinerDirectory ad = airlinerDir;
        //UserProcessContainer.removeAll();
        ManageFlightSchedule msjp = new ManageFlightSchedule (userProcessContainer,flight, airliner, flightSchedule, airplaneList);
        userProcessContainer.add("ManageFlightSchedule",msjp); //any name will do
        ((java.awt.CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
        
        
        
        
        
        
    }//GEN-LAST:event_btnViewFlightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         backAction();
    }                                       

    private void backAction(){
        userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        ManageAirlinersJPanel ms = (ManageAirlinersJPanel) c;
        ms.populateAirlinerList();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    
          
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFlightActionPerformed
        // TODO add your handling code here:
        
        AirlinerDirectory ad = airlinerDir;
        //UserProcessContainer.removeAll();
        CreateNewFlightJPanel msjp = new CreateNewFlightJPanel(userProcessContainer, airliner, flightList);
        userProcessContainer.add("CreateNewFlightJPanel",msjp); //any name will do
        ((java.awt.CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
        
        
        
    }//GEN-LAST:event_btnNewFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewFlight;
    private javax.swing.JButton btnViewFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JTable tblFlight;
    // End of variables declaration//GEN-END:variables
}
