/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise.Insurance;
import Business.Location.LocationPoint;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.Role.PatientRole;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import userinterface.GoogleMAP.AddressJPanel;
import userinterface.ReceptionistRole.ReceptionistWorkAreaJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Suhani
 */
public class CreateNewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewPatientJPanel
     */
   
    JPanel userProcessContainer;
    Organization organization;
    Enterprise enterprise;
    UserAccount userAccount;
    EcoSystem ecosystem;
    LocationPoint locationPoint;
    //Network network;
    public CreateNewPatientJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        if(enterprise.getPatientDirectory() == null){
            PatientDirectory patientDirectory = new PatientDirectory();
            patientDirectory.setPatientList(new ArrayList<Patient>());
            enterprise.setPatientDirectory(patientDirectory);
        }
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        //this.network = network;
        populateMobileCarrierComboBox();
        populateCmbInsurance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblPatientName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JComboBox();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        btnSetLocation = new javax.swing.JButton();
        lblemail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        contactCarrier = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();
        txtInsuranceID = new javax.swing.JTextField();
        lblGender1 = new javax.swing.JLabel();
        cmbInsuranceCompany = new javax.swing.JComboBox();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblUserName2 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lblPatientName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientName.setText("Patient Name:");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 124, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Patient");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 16, 199, -1));

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 166, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Patient Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 124, -1));

        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 124, -1));

        txtGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Male", "Female", "Other" }));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 166, -1));

        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNumber.setText("Phone Number:");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 124, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 166, -1));

        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName.setText("UserName:");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 74, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 166, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Password:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 74, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 166, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Blood Group:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        txtBloodGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 166, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        txtAddress.setEditable(false);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 166, -1));

        btnSetLocation.setText("Set Location");
        btnSetLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLocationActionPerformed(evt);
            }
        });
        add(btnSetLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 166, -1));

        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblemail.setText("Email:");
        add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 129, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 166, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 56, 82));
        jLabel11.setText("Carrier:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 20));

        contactCarrier.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        contactCarrier.setForeground(new java.awt.Color(25, 56, 82));
        contactCarrier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        contactCarrier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactCarrierActionPerformed(evt);
            }
        });
        contactCarrier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactCarrierKeyTyped(evt);
            }
        });
        add(contactCarrier, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 165, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/CreatePatient.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 299, -1));

        lblUserName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName1.setText("Insurance ID:");
        add(lblUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 110, -1));
        add(txtInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 166, -1));

        lblGender1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender1.setText("Insurance Company:");
        add(lblGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 130, -1));

        cmbInsuranceCompany.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Male", "Female", "Other" }));
        add(cmbInsuranceCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 160, -1));

        jPanel14.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        jPanel13.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/createPatient2.PNG"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 640, 340));

        lblUserName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUserName2.setText("SSN:");
        add(lblUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 110, -1));
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 166, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    
    void populateCmbInsurance(){
         cmbInsuranceCompany.removeAllItems();;
        for(Network network : ecosystem.getNetworkList()){
        List<Enterprise> enterprsList = network.getEnterpriseDirectory().getEnterpriseList();
        if (enterprsList == null || enterprsList.isEmpty()) {
            //nothing
        } else {
            for (Enterprise enterprise : enterprsList) {
                if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.Insurance.getValue())) {
                    {
                        cmbInsuranceCompany.addItem(enterprise);
                    }
                }
            }

        }
        }//netowrk for
    }
    
    
    
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(txtPatientName.getText().isEmpty() || txtGender.getSelectedIndex() == 0 ||
                txtPhoneNumber.getText().isEmpty() || txtUserName.getText().isEmpty() ||
                txtPassword.getText().isEmpty() || txtBloodGroup.getSelectedIndex() == 0
                || txtAddress.getText().isEmpty()
                || txtEmail.getText().isEmpty()||
                txtInsuranceID.getText().isEmpty()
                || txtSSN.getText().isEmpty()
                ){
            JOptionPane.showMessageDialog(null, "All fields are mandatory", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String ssnString = txtSSN.getText();
        boolean checkSSN = Validation.checkSNNValidAndUnique(ssnString);
        if(checkSSN == false)
        {
            JOptionPane.showMessageDialog(null, "SSN is invalid", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String emailid= txtEmail.getText();
        boolean valid = Validation.emailValidator(emailid);
        if(valid == false)
        {
            JOptionPane.showMessageDialog(null, "Email ID invalid", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String userName = txtUserName.getText();
       // valid = enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(userName);
        
        //if(valid == false)
        //{
         //   JOptionPane.showMessageDialog(null, "User name exists, try other name", "Warning", JOptionPane.WARNING_MESSAGE);
          //  return;
        //}
        
        
        //check if username is unique
         boolean isUserNameUnique = Validation.checkIfUserNameIsUniqueAcrossNetworks(ecosystem,userName);
        System.out.println("isUserNameUnique: "+ isUserNameUnique);
         if(isUserNameUnique== false)
              {
                  
                  JOptionPane.showMessageDialog(null, "Username already exists, try another name!");
            return;
              }
        String phoneNumberString = txtPhoneNumber.getText();
        
        if(phoneNumberString.length() != 10){
            JOptionPane.showMessageDialog(null, "Phone number is not proper!");
            return;
        }
        
        Insurance insuranceE =(Insurance)cmbInsuranceCompany.getSelectedItem();
        String insuranceId = txtInsuranceID.getText();
        UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(txtUserName.getText(), txtPassword.getText(), null, new PatientRole());
        Employee emp= enterprise.getPatientDirectory().createPatient(txtPatientName.getText(), phoneNumberString, txtGender.getSelectedItem().toString(),
                txtBloodGroup.getSelectedItem().toString(), account, locationPoint, txtEmail.getText(),insuranceE,insuranceId , ssnString);
        
       
        if (contactCarrier.getSelectedItem().equals("ATT")) {
             phoneNumberString="@txt.att.net";
        } else if (contactCarrier.getSelectedItem().equals("Verizon")) {
            phoneNumberString ="@vmobl.com";
        } else if (contactCarrier.getSelectedItem().equals("Sprint")) {
            phoneNumberString =  "@messaging.sprintpcs.com";
        } else if (contactCarrier.getSelectedItem().equals("TMobile")) {
            phoneNumberString = "@tmomail.net";
        }
        emp.setCarrier(phoneNumberString);
        
        JOptionPane.showMessageDialog(null, "Patient added successfully!","Information", JOptionPane.INFORMATION_MESSAGE);
        
        txtPatientName.setText("");
        txtPhoneNumber.setText("");
        txtGender.setSelectedIndex(0);
        txtUserName.setText("");
        txtPassword.setText("");
        txtBloodGroup.setSelectedIndex(0);
        txtAddress.setText("");
        txtEmail.setText("");
        txtInsuranceID.setText("");
        txtSSN.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    
     public void populateMobileCarrierComboBox() {
        contactCarrier.removeAllItems();
        contactCarrier.addItem("ATT");
        contactCarrier.addItem("Sprint");
        contactCarrier.addItem("TMobile");
        contactCarrier.addItem("Verizon");
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray =userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ReceptionistWorkAreaJPanel sysAdminwajp = (ReceptionistWorkAreaJPanel) component;
        
         if(enterprise.getEnterpriseType().getValue().equals("Hospital"))
        {
           sysAdminwajp.populatePatients();
        }
        
        
        if(enterprise.getEnterpriseType().getValue().equals("Lab"))
        {
           sysAdminwajp.populateTest();
        }
        
       // .populatePatients();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateLongituteLatitude(LocationPoint locationPoint) {
        this.locationPoint = locationPoint;
        txtAddress.setText(locationPoint.getLatitude() + ", " + locationPoint.getLongitude());
    }
    
    private void btnSetLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetLocationActionPerformed
        AddressJPanel muajp = new AddressJPanel(userProcessContainer);
        userProcessContainer.add("AddressJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSetLocationActionPerformed

    private void contactCarrierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactCarrierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactCarrierActionPerformed

    private void contactCarrierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactCarrierKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_contactCarrierKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetLocation;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbInsuranceCompany;
    private javax.swing.JComboBox contactCarrier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblemail;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JComboBox txtBloodGroup;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox txtGender;
    private javax.swing.JTextField txtInsuranceID;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
