/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.Uber;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.UIManager;
import javax.swing.plaf.SliderUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditi
 */
public class DisplayCarDateList extends javax.swing.JPanel {

    /**
     * Creates new form DisplayCarDateList
     */
    ArrayList<Car> carList; 
    JSplitPane sp;
    JPanel rjp;
     Uber obj;
    /**
     * Creates new form DisplayCarList
     */
    public DisplayCarDateList(ArrayList<Car> carList, JSplitPane sp, JPanel rjp, Uber obj) {
        initComponents();
    
        this.carList=carList;
        this.sp=sp;
        this.rjp=rjp;
        this.obj= obj;
        populate();
    }

    
    private void populate(){
        /*DefaultTableModel model ;
        model = new DefaultTableModel();
        tblCarDate.setModel(model);
        for(Car s: carList){
            
            model.addRow(new Object[]{s.getCarName().toString(), s.getMaintenanceCertiDate()});
            }*/
        carList=(ArrayList)obj.getCarListByExpCerti();
        
         ArrayList<Car> clist=carList;
        DefaultTableModel dtm = (DefaultTableModel)tblCarDate.getModel();
        dtm.setRowCount(0);
        for(Car c :clist){
            Object[] row= new Object[2];
            row[0]=c.getCarName();
            row[1]=c.getMaintenanceCertiDate();
            dtm.addRow(row);
        }
    }

    public void refreshTable(){
    populate();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarDate = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        tblCarDate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarDate);

        btnView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search On this Set");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addGap(66, 66, 66)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnSearch))
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarDate.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            //Car car= obj.getAvailableCarList().get(selectedRow);
            //ViewCarJPanel panel =new ViewCarJPanel(car,obj);
            //sp.setRightComponent(panel);
            
            
            
            int column = 0;
            int row = tblCarDate.getSelectedRow();
            String value = tblCarDate.getModel().getValueAt(row, column).toString();
            Car car = null;
            for (Car c :  obj.getAvailableCarList()){
                if(c.getCarName().equals(value)){
                    car=c;
                    break;
                }
            }
            for (Car c :  obj.getBookedCarList()){
                if(c.getCarName().equals(value)){
                    car=c;
                    break;
                }
            }
            ViewCarJPanel panel =new ViewCarJPanel(car,obj,sp,this);
            sp.setRightComponent(panel);
            
        }

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Uber newUobj=new Uber();
        if(carList==null){
            JOptionPane.showMessageDialog(null, "No data");
            return;
        }

        for(Car c:carList){
            if(c.getAvailable().equals("A"))
            {
                newUobj.getAvailableCarList().add(c);
            }
            else{
                newUobj.getBookedCarList().add(c);
            }
        }

        SearchJPanel panel = new SearchJPanel(sp,newUobj,this);
        sp.setRightComponent(panel);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rjp.toString();
        sp.setRightComponent(rjp);
    }//GEN-LAST:event_btnBackActionPerformed
@Override
    public String toString() {
      //setUI((SliderUI)UIManager.getUI(this));
      //initComponents();
      refreshTable();
      return "ok";
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarDate;
    // End of variables declaration//GEN-END:variables
}
