/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.Uber;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.UIManager;
import javax.swing.plaf.SliderUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditi
 */
public class DisplayCarManufacturer extends javax.swing.JPanel {

    ArrayList<String> manufacturer;
    Uber uobj;
    JSplitPane splitPane;
    JPanel previousPanel;
    /**
     * Creates new form DisplayCarManufacturer
     */
    public DisplayCarManufacturer(Uber uobj, JSplitPane splitPane,JPanel previousPanel) {
        initComponents();
        this.uobj=uobj;
        this.splitPane=splitPane;
        this.previousPanel=previousPanel;
        populate();
    }

    
    private void populate(){
    ArrayList<String> manufacturer = (ArrayList)uobj.getFleetManufacturerList();
    DefaultTableModel dtm = (DefaultTableModel)tblCarManufacturer.getModel();
        dtm.setRowCount(0);
        for(String c :manufacturer){
            Object[] row= new Object[1];
            row[0]=c;
            //row[1]=c.getCity();
            dtm.addRow(row);
        }
        
        
        
}




public void refreshTable(){
    populate();
    
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarManufacturer = new javax.swing.JTable();
        btnSearchCar = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblCarManufacturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarManufacturer);

        btnSearchCar.setText("Search Cars");
        btnSearchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchCar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnBack)))
                .addGap(36, 36, 36)
                .addComponent(btnSearchCar)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarManufacturer.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            int column = 0;
            int row = tblCarManufacturer.getSelectedRow();
            String manu = tblCarManufacturer.getModel().getValueAt(row, column).toString();
            
            //ViewCarJPanel panel =new ViewCarJPanel(car,obj);
            Map<String,ArrayList<Car>> mapObj= new HashMap<String,ArrayList<Car>>();
            ArrayList<Car> carList = new ArrayList<Car>();
            for(Car c: uobj.getAvailableCarList())
            {
                if(c.getManufacturer().equals(manu)){
                    carList.add(c);
                }
            }
            for(Car c: uobj.getBookedCarList())
            {
                if(c.getManufacturer().equals(manu)){
                    carList.add(c);
                }
            }
            mapObj.put(manu,carList);
        
        DisplayJPanel panel = new DisplayJPanel(mapObj, uobj,  splitPane,this);
        splitPane.setRightComponent(panel);
        }
    }//GEN-LAST:event_btnSearchCarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        previousPanel.toString();
        splitPane.setRightComponent(previousPanel);
    }//GEN-LAST:event_btnBackActionPerformed

 @Override
    public String toString() {
      //setUI((SliderUI)UIManager.getUI(this));
      //initComponents();
      refreshTable();
      return "ok";
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchCar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarManufacturer;
    // End of variables declaration//GEN-END:variables
}
